// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H


#ifdef __cplusplus
extern "C" {
#endif

void udf_VideoSteam_Play(lv_event_t * e);
void udf_VideoSteam_Stop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
