// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#include "ui.h"
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

// Flags shared with main.c to control the stream task state
volatile bool is_video_streaming = false;

void udf_VideoSteam_Play(lv_event_t * e)
{
    if (!is_video_streaming) {
        is_video_streaming = true;
        printf("[ESP32-P4] Video stream requested: START\n");
    }
}

void udf_VideoSteam_Stop(lv_event_t * e)
{
    if (is_video_streaming) {
        is_video_streaming = false;
        printf("[ESP32-P4] Video stream requested: STOP\n");
    }
}
