// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#ifndef UI_SCRTWO_H
#define UI_SCRTWO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrTwo
extern void ui_scrTwo_screen_init(void);
extern void ui_scrTwo_screen_destroy(void);
extern lv_obj_t * ui_scrTwo;
extern void ui_event_btnGoToScrMain(lv_event_t * e);
extern lv_obj_t * ui_btnGoToScrMain;
extern lv_obj_t * ui_Label2;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Slider1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrTwo;
extern lv_obj_t * uic_btnGoToScrMain;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

