// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#include "../ui.h"

lv_obj_t * uic_lblBtnStop;
lv_obj_t * uic_lblBtnBack;
lv_obj_t * uic_lblBtnStart;
lv_obj_t * uic_btnStart;
lv_obj_t * uic_pnlBtns;
lv_obj_t * uic_imgCameraView;
lv_obj_t * uic_scrCameraView;
lv_obj_t * ui_scrCameraView = NULL;
lv_obj_t * ui_imgCameraView = NULL;
lv_obj_t * ui_pnlBtns = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_btnGoToScrMain2 = NULL;
lv_obj_t * ui_btnStart = NULL;
lv_obj_t * ui_btnStop = NULL;
lv_obj_t * ui_lblBtnStart = NULL;
lv_obj_t * ui_lblBtnBack = NULL;
lv_obj_t * ui_lblBtnStop = NULL;
// event funtions
void ui_event_btnGoToScrMain2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_btnStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        udf_VideoSteam_Play(e);
    }
}

void ui_event_btnStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        udf_VideoSteam_Stop(e);
    }
}

// build funtions

void ui_scrCameraView_screen_init(void)
{
    ui_scrCameraView = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrCameraView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrCameraView, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrCameraView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgCameraView = lv_image_create(ui_scrCameraView);
    lv_obj_set_width(ui_imgCameraView, 360);
    lv_obj_set_height(ui_imgCameraView, 240);
    lv_obj_set_x(ui_imgCameraView, -2);
    lv_obj_set_y(ui_imgCameraView, -10);
    lv_obj_set_align(ui_imgCameraView, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgCameraView, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgCameraView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_imgCameraView, lv_color_hex(0x066A37), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgCameraView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgCameraView, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlBtns = lv_obj_create(ui_scrCameraView);
    lv_obj_set_width(ui_pnlBtns, 503);
    lv_obj_set_height(ui_pnlBtns, 53);
    lv_obj_set_x(ui_pnlBtns, -1);
    lv_obj_set_y(ui_pnlBtns, 135);
    lv_obj_set_align(ui_pnlBtns, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pnlBtns, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlBtns, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlBtns, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_pnlBtns, lv_color_hex(0x06623D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlBtns, lv_color_hex(0x03662F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlBtns, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pnlBtns, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_scrCameraView);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -26);
    lv_obj_set_y(ui_Label5, -145);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Поток видео с камеры MIPI-CSI");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnGoToScrMain2 = lv_button_create(ui_scrCameraView);
    lv_obj_set_width(ui_btnGoToScrMain2, 100);
    lv_obj_set_height(ui_btnGoToScrMain2, 36);
    lv_obj_set_x(ui_btnGoToScrMain2, -177);
    lv_obj_set_y(ui_btnGoToScrMain2, 135);
    lv_obj_set_align(ui_btnGoToScrMain2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnGoToScrMain2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnGoToScrMain2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_btnGoToScrMain2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnGoToScrMain2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnGoToScrMain2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnGoToScrMain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnGoToScrMain2, lv_color_hex(0x046738), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnGoToScrMain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnGoToScrMain2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnStart = lv_button_create(ui_scrCameraView);
    lv_obj_set_width(ui_btnStart, 100);
    lv_obj_set_height(ui_btnStart, 36);
    lv_obj_set_x(ui_btnStart, -23);
    lv_obj_set_y(ui_btnStart, 135);
    lv_obj_set_align(ui_btnStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnStart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnStart, lv_color_hex(0x056529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnStart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnStop = lv_button_create(ui_scrCameraView);
    lv_obj_set_width(ui_btnStop, 100);
    lv_obj_set_height(ui_btnStop, 36);
    lv_obj_set_x(ui_btnStop, 139);
    lv_obj_set_y(ui_btnStop, 135);
    lv_obj_set_align(ui_btnStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnStop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnStop, lv_color_hex(0x056529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnStop, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBtnStart = lv_label_create(ui_scrCameraView);
    lv_obj_set_width(ui_lblBtnStart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBtnStart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBtnStart, -23);
    lv_obj_set_y(ui_lblBtnStart, 135);
    lv_obj_set_align(ui_lblBtnStart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBtnStart, "Старт >");
    lv_obj_set_style_text_font(ui_lblBtnStart, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBtnBack = lv_label_create(ui_scrCameraView);
    lv_obj_set_width(ui_lblBtnBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBtnBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBtnBack, -175);
    lv_obj_set_y(ui_lblBtnBack, 135);
    lv_obj_set_align(ui_lblBtnBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBtnBack, "<< Назад");
    lv_obj_set_style_text_font(ui_lblBtnBack, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBtnStop = lv_label_create(ui_scrCameraView);
    lv_obj_set_width(ui_lblBtnStop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBtnStop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBtnStop, 137);
    lv_obj_set_y(ui_lblBtnStop, 135);
    lv_obj_set_align(ui_lblBtnStop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBtnStop, "Стоп ||");
    lv_obj_set_style_text_font(ui_lblBtnStop, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnGoToScrMain2, ui_event_btnGoToScrMain2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStart, ui_event_btnStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStop, ui_event_btnStop, LV_EVENT_ALL, NULL);
    uic_scrCameraView = ui_scrCameraView;
    uic_imgCameraView = ui_imgCameraView;
    uic_pnlBtns = ui_pnlBtns;
    uic_btnStart = ui_btnStart;
    uic_lblBtnStart = ui_lblBtnStart;
    uic_lblBtnBack = ui_lblBtnBack;
    uic_lblBtnStop = ui_lblBtnStop;

}

void ui_scrCameraView_screen_destroy(void)
{
    if(ui_scrCameraView) lv_obj_del(ui_scrCameraView);

    // NULL screen variables
    uic_scrCameraView = NULL;
    ui_scrCameraView = NULL;
    uic_imgCameraView = NULL;
    ui_imgCameraView = NULL;
    uic_pnlBtns = NULL;
    ui_pnlBtns = NULL;
    ui_Label5 = NULL;
    ui_btnGoToScrMain2 = NULL;
    uic_btnStart = NULL;
    ui_btnStart = NULL;
    ui_btnStop = NULL;
    uic_lblBtnStart = NULL;
    ui_lblBtnStart = NULL;
    uic_lblBtnBack = NULL;
    ui_lblBtnBack = NULL;
    uic_lblBtnStop = NULL;
    ui_lblBtnStop = NULL;

}
