// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#include "../ui.h"

lv_obj_t * uic_btnCW;
lv_obj_t * uic_TextArea1;
lv_obj_t * uic_Label1;
lv_obj_t * uic_scrMain;
lv_obj_t * ui_scrMain = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_btnCW = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_btnCW1 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_btnCW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTwo, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_scrTwo_screen_init);
    }
}

void ui_event_btnCW1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrCameraView, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_scrTwo_screen_init);
    }
}

// build funtions

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -27);
    lv_obj_set_y(ui_Label1, -103);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "ddthfdhfhj");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_scrMain);
    lv_obj_set_width(ui_TextArea1, 286);
    lv_obj_set_height(ui_TextArea1, 37);
    lv_obj_set_x(ui_TextArea1, -4);
    lv_obj_set_y(ui_TextArea1, -57);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea1, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCW = lv_button_create(ui_scrMain);
    lv_obj_set_width(ui_btnCW, 171);
    lv_obj_set_height(ui_btnCW, 61);
    lv_obj_set_x(ui_btnCW, -100);
    lv_obj_set_y(ui_btnCW, 102);
    lv_obj_set_align(ui_btnCW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnCW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnCW, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnCW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnCW, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnCW, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnCW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -11);
    lv_obj_set_y(ui_Label3, -143);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Тест русского ПРОБА");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -101);
    lv_obj_set_y(ui_Label4, 102);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Жмяк");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_ftRbBlck18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCW1 = lv_button_create(ui_scrMain);
    lv_obj_set_width(ui_btnCW1, 171);
    lv_obj_set_height(ui_btnCW1, 61);
    lv_obj_set_x(ui_btnCW1, 100);
    lv_obj_set_y(ui_btnCW1, 101);
    lv_obj_set_align(ui_btnCW1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCW1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnCW1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_btnCW1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnCW1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnCW1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnCW1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnCW1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 100);
    lv_obj_set_y(ui_Label6, 102);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Video");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_ftRbBlck18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnCW, ui_event_btnCW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCW1, ui_event_btnCW1, LV_EVENT_ALL, NULL);
    uic_scrMain = ui_scrMain;
    uic_Label1 = ui_Label1;
    uic_TextArea1 = ui_TextArea1;
    uic_btnCW = ui_btnCW;

}

void ui_scrMain_screen_destroy(void)
{
    if(ui_scrMain) lv_obj_del(ui_scrMain);

    // NULL screen variables
    uic_scrMain = NULL;
    ui_scrMain = NULL;
    uic_Label1 = NULL;
    ui_Label1 = NULL;
    uic_TextArea1 = NULL;
    ui_TextArea1 = NULL;
    uic_btnCW = NULL;
    ui_btnCW = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_btnCW1 = NULL;
    ui_Label6 = NULL;

}
