// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#include "../ui.h"

lv_obj_t * uic_btnGoToScrMain;
lv_obj_t * uic_scrTwo;
lv_obj_t * ui_scrTwo = NULL;
lv_obj_t * ui_btnGoToScrMain = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Slider1 = NULL;
// event funtions
void ui_event_btnGoToScrMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(ui_Slider1, -1, LV_ANIM_ON);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(ui_Slider1, 1, LV_ANIM_ON);
    }
}

// build funtions

void ui_scrTwo_screen_init(void)
{
    ui_scrTwo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrTwo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrTwo, lv_color_hex(0x187F76), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrTwo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_scrTwo, lv_color_hex(0x466D78), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnGoToScrMain = lv_button_create(ui_scrTwo);
    lv_obj_set_width(ui_btnGoToScrMain, 180);
    lv_obj_set_height(ui_btnGoToScrMain, 114);
    lv_obj_set_align(ui_btnGoToScrMain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGoToScrMain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnGoToScrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_scrTwo);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -3);
    lv_obj_set_y(ui_Label2, -2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Go To Main");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_ftRbBlck14b1n111, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_scrTwo);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -171);
    lv_obj_set_y(ui_Button1, -35);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_scrTwo);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 168);
    lv_obj_set_y(ui_Button2, -30);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_scrTwo);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 328);
    lv_obj_set_height(ui_Slider1, 16);
    lv_obj_set_x(ui_Slider1, -4);
    lv_obj_set_y(ui_Slider1, -133);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_btnGoToScrMain, ui_event_btnGoToScrMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    uic_scrTwo = ui_scrTwo;
    uic_btnGoToScrMain = ui_btnGoToScrMain;

}

void ui_scrTwo_screen_destroy(void)
{
    if(ui_scrTwo) lv_obj_del(ui_scrTwo);

    // NULL screen variables
    uic_scrTwo = NULL;
    ui_scrTwo = NULL;
    uic_btnGoToScrMain = NULL;
    ui_btnGoToScrMain = NULL;
    ui_Label2 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Slider1 = NULL;

}
