// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#ifndef UI_SCRCAMERAVIEW_H
#define UI_SCRCAMERAVIEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrCameraView
extern void ui_scrCameraView_screen_init(void);
extern void ui_scrCameraView_screen_destroy(void);
extern lv_obj_t * ui_scrCameraView;
extern lv_obj_t * ui_imgCameraView;
extern lv_obj_t * ui_pnlBtns;
extern lv_obj_t * ui_Label5;
extern void ui_event_btnGoToScrMain2(lv_event_t * e);
extern lv_obj_t * ui_btnGoToScrMain2;
extern void ui_event_btnStart(lv_event_t * e);
extern lv_obj_t * ui_btnStart;
extern void ui_event_btnStop(lv_event_t * e);
extern lv_obj_t * ui_btnStop;
extern lv_obj_t * ui_lblBtnStart;
extern lv_obj_t * ui_lblBtnBack;
extern lv_obj_t * ui_lblBtnStop;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrCameraView;
extern lv_obj_t * uic_imgCameraView;
extern lv_obj_t * uic_pnlBtns;
extern lv_obj_t * uic_btnStart;
extern lv_obj_t * uic_lblBtnStart;
extern lv_obj_t * uic_lblBtnBack;
extern lv_obj_t * uic_lblBtnStop;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

