// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: l01

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_TextArea1;
extern void ui_event_btnCW(lv_event_t * e);
extern lv_obj_t * ui_btnCW;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern void ui_event_btnCW1(lv_event_t * e);
extern lv_obj_t * ui_btnCW1;
extern void ui_event_Label6(lv_event_t * e);
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_scrMain;
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_TextArea1;
extern lv_obj_t * uic_btnCW;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

